### PR TITLE
Search entities enrichment functionality #992

### PR DESCRIPTION
**Pull request by CaitlinOCallaghan**
- add functionality to search bar in toolbar 
- allow for searching by node label ('description') and 'geneSet'
image

### CODE REVIEW

**Comment by d2fong** [comment]
@maxkfranz @jvwong @q4wen @MichaelWrana thoughts on the highlight colours/functionality?

**Comment by maxkfranz** [comment]
Maybe it would be better to just use the bg colour like the pathway viewer does.  For enrichment and sif cases, you could also make the text outline colour yellow -- that helps with small nodes.

**Comment by MichaelWrana** [comment]
this is a bit much BUT maybe have similar functionality to apple-f on browsers.  Searching a gene would put some arrows below the search bar, then zoom in and centre each node as you click through the list (by clicking the arrows).  Then highlighting could be used to clear up the SBGN view.

**Comment by jvwong** [comment]
Works for me.

**Comment by CaitlinOCallaghan** [comment]
image

**Pull request merged**
