### PR TITLE
V.2.1.0

### PR DESCRIPTION
**Pull request by d2fong**
Preparing for release v2.1.0

### CODE REVIEW

**Comment by d2fong** [comment]
@jvwong @maxkfranz @IgorRodchenkov this branch is deployed to appsbeta for pre release to production.  

@jvwong is there anything you think needs to be added to this release?

**Comment by jvwong** [comment]
No, in fact we should release ASAP since the last one is 'broken' due to g:Profiler archived version returning 503.

**Comment by jvwong** [comment]
Also is there an easy way to clear out the appsbeta VM rethink database/tables?

**Comment by IgorRodchenkov** [comment]
> Also is there an easy way to clear out the appsbeta VM rethink database/tables?

I belive this can be done at http://192.168.81.195:8888/

**Comment by IgorRodchenkov** [comment]
@jvwong @d2fong 
Please don't delete all the rethinkdb tables/dbs blindly (i.e., yeast one should brobably not be touched)

**Comment by IgorRodchenkov** [comment]
I belive this can be done at http://192.168.81.195:8888/
:)

**Comment by d2fong** [comment]
Btw I don't think its the greatest idea to share the location of our db admin console publicly.

**Pull request merged**
