### PR TITLE
Expand collapse cue

### PR DESCRIPTION
**Pull request by d2fong**
- adds expand collapse cue for each node on hover.  
- uses tippy tooltips to implement the cue
- 'meta edges' from the expand collapse library are dashed to communicate that they are 'meta edges'
- many subtle complexities and edge cases are handled but there are probably more that I can't think of right now.

screen shot 2018-07-31 at 10 28 40 am
screen shot 2018-07-31 at 10 28 30 am
screen shot 2018-07-31 at 10 28 25 am

### CODE REVIEW

**Comment by d2fong** [comment]
- also it doesn't work on mobile

**Comment by maxkfranz** [comment]
For mobile, one possibility is to show the cue after tapping the node -- since you don't have hover on mobile.

**Comment by jvwong** [comment]
One general observations: The nodes that aren't being expanded/collapsed are being shifted around, sometimes off screen. I'd expect it to be static.

**Comment by d2fong** [comment]
thats a laser cat cose-bilkent thing that makes it look good.

**Comment by d2fong** [comment]
I'm just gonna merge this now, if we find out that we don't want cues down the road we can just remove them.

**Pull request merged**
