### PR TITLE
add a basic test for gconvert validator

### PR DESCRIPTION
**Pull request by wxli0**
relates to #475

### CODE REVIEW

**Comment by jvwong** [comment]
Can I suggest 1. Making related issue titles a little more informative 2. Adding some Documentation comments to the empty files?

**Comment by d2fong** [comment]
I think the problem here is that all these empty files should go in a different PR.

@wxli0 this PR has two things:
- adding a bunch of empty files (which is fine, but the PR title says added a test so there is a disconnect between what you are presenting and what you are actually doing)
- added a test for gconvert validator, which is fine too because that is what the PR says to do.

I dont think its useful to add comments to the empty files thats a waste of time.  The empty files are just for folder structure so its better organized.

**Comment by wxli0** [comment]
yea they seem to be dependent on each other. I should have only added the test and then merge it with pr #476 once the review is done.
@jvwong #475 name has been changed

**Comment by d2fong** [comment]
Yeah so do that next time, I am just gonna merge this because we already talked about it, but again this is really important.  At the very least, your PR title should have been something like:

Add folder structure for the enrichment map services, add basic test for gconvert validation

**Pull request merged**
