### PR TITLE
Enrichment example input #1020

### PR DESCRIPTION
**Pull request by CaitlinOCallaghan**
- example input for enrichment set to: "tyr, oca2, tyrp1, slc45a2"  
(chosen because of quick loading time and variation in node sizes and colours)

- text colour change on hover 'e.g.' 
- 'e.g.' disappears once any text is typed into input box
- input box opens when example input is selected

image
image
Resulting Network
image

### CODE REVIEW

**Comment by jvwong** [comment]
Do those genes have any particular meaning?

**Comment by CaitlinOCallaghan** [comment]
The genes are those known to cause albinism. I thought it would be good to use a list where the node names made sense (pigmentation, melanin, vision) with the input. I also considered the network , variation in node sizes and colors, and quick loading speed.

**Comment by CaitlinOCallaghan** [comment]
The input list can be easily changed if we would prefer to use a different set

**Comment by jvwong** [comment]
Oh I just wanted to be prepared for any questions - the results do seem to make sense though!

**Pull request merged**
