### PR TITLE
interactions button and minor entity info box tweaks

### PR DESCRIPTION
**Pull request by d2fong**
- text for sub fields (name, description, other names) is smaller than the title label
- places the button in the center of the screen
- more padding between interactions results and pathway results

- open to design suggestions
screen shot 2018-09-10 at 1 29 45 pm

### CODE REVIEW

**Comment by jvwong** [comment]
This is great. I am probably in too deep to know if that interaction button will be effective. Maybe ask around now?

**Comment by maxkfranz** [comment]
One option is to show the interactions link as an entry, just like all the other pathway entries.  We could come up with a logo that makes it clear that you're going to a SIF view.

**Comment by maxkfranz** [comment]
Title ideas:

- 1 gene input : Interactions with TP53
- 2 gene input : Interactions between TP53 and MDM2
- 3 gene input : Interactions between TP53, MDM2, and RAD51

**Comment by d2fong** [comment]
i'll just merge this and if someone has strong opinions we can change it after.

**Pull request merged**
