### PR TITLE
Replace `cy.mount()` with `CytoscapeService`

### PR DESCRIPTION
**Pull request by maxkfranz**
This PR replaces the cytoscape#unstable ref in package.json with cytoscape@3.2.14.  This is an initial pass at the change, but more commits may be necessary.  There may be issues in the SIF viewer, for example.

- Use CytoscapeService as a way to pass around a not yet existent Cytoscape instance
- Use cytoscape@3.2.14
- Search, pathway viewer, and paint seem OK

### CODE REVIEW

**Comment by maxkfranz** [comment]
Ref : Zoom on causing network views to cut off #878

**Comment by maxkfranz** [comment]
@jvwong Does this branch fix #878 on your machine?

**Comment by jvwong** [comment]
yes looks good to me.

**Comment by maxkfranz** [comment]
Great.  @d2fong, let me know if you notice any problems with this PR and I'll address them.  Or feel free to make changes directly on the `cytoscapenpm` branch, if you like.

**Pull request merged**
