### PR TITLE
Modified Hover to only change opacity

### PR DESCRIPTION
**Pull request by MichaelWrana**
Refs #868 #870 
Reworked the hover functionality to only modify opacity.
Some screenshots of how the new hover will look:
screen shot 2018-07-11 at 11 33 09 am
screen shot 2018-07-11 at 11 32 45 am
screen shot 2018-07-11 at 11 32 30 am

### CODE REVIEW

**Comment by d2fong** [comment]
Neat

**Comment by d2fong** [comment]
Waiting on Jeff/Gary feedback

**Comment by maxkfranz** [comment]
Re. the code, it shouldn't be applying bypasses.  It should be using the stylesheet.  This would drastically simplify the code.

Classes:

- highlighted
- unhighlighted

Adding highlight:

```js
elesToHighlight.addClass('highlighted');

cy.elements().difference(elesToHighlight).addClass('unhighlighted');
```

Clearing:

```js
cy.elements().removeClass('highlighted unhighlighted');
```

**Comment by MichaelWrana** [comment]
When I want to create a new CSS class, e.g. `highlighted` and `unhighlighted` and add it to different network views, it looks like I have to add them all identically to:

`src/client/common/cy/stylesheet.js`
`src/client/common/cy/interactions-stylesheet.js`
`src/client/common/cy/enrichment-stylesheet.js`

This works, but seems pretty prone to breaking in future (eg someone creating a new view and not adding these classes).  Maybe we should create a generic `stylesheet.js` somewhere that applies to all views?  Or this already exists and I missed it?

**Comment by maxkfranz** [comment]
There should be a default stylesheet, and the other specific stylesheets can extend them.  If you use a JSON stylesheet, then

```
let stylesheet = [ /* basic style that applies to all views */ ];

let specificStylesheet = stylesheet.concat([ /* new style blocks on top... */ ])
```

**Comment by jvwong** [comment]
This is a great solution, leaves the door open to better use highlight for other tasks (e.g. selection). I can't run branch locally b/c of conflicts...

**Comment by jvwong** [comment]
@MichaelWrana I don't find this feature present after the merge?

**Pull request merged**
