### PR TITLE
Database Unit Tests

### PR DESCRIPTION
**Pull request by gaelder**

### CODE REVIEW

**Comment by d2fong** [comment]
If someone wants to run the tests do they have to do anything special or is it just ```npm run test```?

**Comment by gaelder** [comment]
I just checked, no npm run test does not work. Should I move the test files to the /test/ instead of organizing them in folders?

**Comment by d2fong** [comment]
What command do you use to run the tests?

**Comment by gaelder** [comment]
I had just been running each file individually with mocha _file_

**Comment by d2fong** [comment]
Do the tests run if you just type ```mocha```?

**Comment by gaelder** [comment]
No

**Comment by d2fong** [comment]
Okay so in package.json, under npm scripts, you can set that command to run ```mocha --recursive```

**Comment by d2fong** [comment]
Can you paste the output of just running ```mocha``` it is strange that you need the recursive flag for all the tests to run.

**Comment by gaelder** [comment]
This is the output.
`  Example
    ✓ does something
    ✓ does something else


  2 passing (11ms)`

I have my tests in a subdirectory of /test because I figured I should be mirroring the directory structure of /src, hence the need for the flag

**Comment by d2fong** [comment]
https://stackoverflow.com/questions/10753288/how-to-specify-test-directory-for-mocha

Can you try something similar to:
```mocha "test/**/*.js"```

**Comment by gaelder** [comment]
```mocha "test/**/*.js``` has the same output as ```mocha --recursive```

**Comment by d2fong** [comment]
Okay so I guess they both do something similar.

**Pull request merged**
