### PR TITLE
Infobox description more-less style changes

### PR DESCRIPTION
**Pull request by q4wen**
Info box description is now always truncated to 2 lines initially. ref: #733

### CODE REVIEW

**Comment by maxkfranz** [comment]
Would you attach a before-and-after screenshot, please?

**Comment by q4wen** [comment]
Before:
before_less


before_more
<br/><br/><br/>
After:
screen shot 2018-05-15 at 9 13 53 am
<br/>
screen shot 2018-05-15 at 9 14 16 am

**Comment by maxkfranz** [comment]
@jvwong @d2fong How does this look to you?

I think the feature itself looks fine.  Maybe there could be a margin around the description paragraph to give a bit more spacing -- but that's pretty minor.

**Comment by d2fong** [comment]
I think it is better now that it is using css instead of some hardcoded values in js.  Improving the styling / refactoring this probably needs to be its own ticket.

**Pull request merged**
