### PR TITLE
update

### PR DESCRIPTION
**Pull request by wxli0**
endpoint doesn't work

### CODE REVIEW

**Comment by wxli0** [comment]
@d2fong Hi Dylan, I didn't find how the search endpoint was implemented in routes/rest.js. Could you let me know where it is? 
It seems that all functions in controller.js are related to database/. Maybe I need to add a file to database folder? Is there a similar function I can refer to?

**Comment by d2fong** [comment]
What search endpoint are you referring to?

**Comment by wxli0** [comment]
http://localhost:3000/search

**Comment by d2fong** [comment]
closing old prs

**Pull request closed without merging**
